### ISSUE TITLE
Camera Quality

### ISSUE THREAD

**Issue by markrickert** [a1phanumeric/iPhone-AR-Toolkit#1]
It appears as though the image being piped through the ARViewController is not running at the full resolution of the camera. It's very pixelated.

Screenshot - you can see the pixelation on the edge of the computer monitor:
![IMG_4981](https://f.cloud.github.com/assets/139261/54016/11bc91e2-5a7f-11e2-97ac-4d2d6460cfd4.PNG)

**Comment by a1phanumeric** [comment]
20aad782b7f8342cafbf23a77462b3186a084ade

Camera now uses high quality. Will make into a config option in the future.

**Comment by markrickert** [comment]
Lol... well that was easy! Ha!
