### ISSUE TITLE
View Controller Doesn't Respect the Parent View Controller's Size

### ISSUE THREAD

**Issue by markrickert** [a1phanumeric/iPhone-AR-Toolkit#2]
It looks like the ARViewController is mean to be run full screen, but when putting it inside of another viewController or a UINavigationController, it should position elements correctly inside the parent view controller's view.

Screenshots with highlighted positioning issues:

![IMG_4982](https://f.cloud.github.com/assets/139261/54059/5a5d629a-5a80-11e2-995a-babddc8bd217.PNG)

![IMG_4983](https://f.cloud.github.com/assets/139261/54061/5df302f2-5a80-11e2-997d-a2fa672ed831.PNG)

**Comment by a1phanumeric** [comment]
Looking into...

**Comment by a1phanumeric** [comment]
Almost done - I'll upload the code tomorrow.

Just before I do close this issue - I will have fixed the following issues:
- Horizontal orientation where the navigation bar or tab bar is present
- When rotating back to portrait, and specifically when using both a tab bar and navigation bar, the frame is too large. (Note: when using a navigation bar only, this works fine)

### Working Screenshots

![iOS Simulator Screen shot 15 Jan 2013 00 48 07](https://f.cloud.github.com/assets/307149/66532/884199e8-5ead-11e2-9af0-ea13d43199d3.png)
![iOS Simulator Screen shot 15 Jan 2013 00 50 33](https://f.cloud.github.com/assets/307149/66534/938e0f7a-5ead-11e2-82be-651447416ba3.png)
![iOS Simulator Screen shot 15 Jan 2013 00 50 43](https://f.cloud.github.com/assets/307149/66535/9b660fcc-5ead-11e2-8367-93a66dc7c187.png)

### Non-Working Screenshots

![iOS Simulator Screen shot 15 Jan 2013 00 50 56](https://f.cloud.github.com/assets/307149/66536/a25f02e8-5ead-11e2-8f4f-ee6410fbc427.png)
This was after rotation

![iOS Simulator Screen shot 15 Jan 2013 00 52 33](https://f.cloud.github.com/assets/307149/66542/dbcb03ec-5ead-11e2-8302-114a6486e0c7.png)
This happens whenever a navigation bar is used - but will self-right when not using a tab bar.

**Comment by a1phanumeric** [comment]
Hopefully fixed. See 0d0c5f4e92757e6f93e4d4fbaf3f52669f64f466
