### ISSUE TITLE
location points(white color dots) not showing in the radar view

### ISSUE THREAD

**Issue by karthikprabhuA** [a1phanumeric/iPhone-AR-Toolkit#8]
location points(white color dots) not showing in the radar view.
![ar_locationdots](https://f.cloud.github.com/assets/1456465/870876/07d9d3c6-f839-11e2-9299-1ccf0cdb69bd.jpg)

For your reference i used the following locations:

My current location - 12.829251,80.216331
- (NSMutableArray *)geoLocations{
  
  NSMutableArray *locationArray = [[NSMutableArray alloc] init];
  ARGeoCoordinate *tempCoordinate;
  CLLocation       *tempLocation;
  
  tempLocation = [[CLLocation alloc] initWithLatitude:12.829251 longitude:80.216331];
  tempCoordinate = [ARGeoCoordinate coordinateWithLocation:tempLocation locationTitle:@"Denver"];
  [locationArray addObject:tempCoordinate];
  
  tempLocation = [[CLLocation alloc] initWithLatitude:12.827326 longitude:80.219271];
  tempCoordinate = [ARGeoCoordinate coordinateWithLocation:tempLocation locationTitle:@"Portland"];
  [locationArray addObject:tempCoordinate];
  
  tempLocation = [[CLLocation alloc] initWithLatitude:12.826489 longitude:80.219207];
  tempCoordinate = [ARGeoCoordinate coordinateWithLocation:tempLocation locationTitle:@"Chicago"];
  [locationArray addObject:tempCoordinate];
  
  tempLocation = [[CLLocation alloc] initWithLatitude:12.831929 longitude:80.223799];
  tempCoordinate = [ARGeoCoordinate coordinateWithLocation:tempLocation locationTitle:@"Austin"];
  [locationArray addObject:tempCoordinate];
  return locationArray;
  }.

please help me to solve this issue

**Comment by a1phanumeric** [comment]
Hey,

Are these points over 20km from your location? By default, the radar's maximum range is 20km. You can change this using the `setRadarRange:` method.

Ed.

**Comment by karthikprabhuA** [comment]
Thanks for your quick response.
No these points are within 20km from my location.
setting radar range as   [_arViewController setRadarRange:4000.0];

**Comment by karthikprabhuA** [comment]
Hi,
Now i removed the following line and i can able to see the dots, but dots are very close to each other. 
how to solve ?

  //[_arViewController setRadarRange:4000.0];
   // [_arViewController setOnlyShowItemsWithinRadarRange:YES];

**Comment by viral105** [comment]
Hi,

I am having the same issue.
I tried removing both this line
//[_arViewController setRadarRange:4000.0];
// [_arViewController setOnlyShowItemsWithinRadarRange:YES];

My locations are within 20 km,
but still not getting this kind of locations dots.

Anyone have solution for this issue ?

**Comment by a1phanumeric** [comment]
What point has the furthest distance? You should set your radar range to this value (or just above).

What's happening is (for example) if your points are all within ONE km but your range is set to 20km, then all of your points would be in the centre of the circle. If you set your range to 1km, they would display correctly (provided all of your points are within 1km).

Does that make sense?

**Comment by viral105** [comment]
a1phanumeric thanks for comment.

I have set all points within 1 km range and set radar range like this

[_arViewController setRadarRange:1000.0];

still all the points showing at the center of circle.

**Comment by a1phanumeric** [comment]
What happens if you set your radar range to 1? Like so:

[_arViewController setRadarRange:1.0];

**Comment by karthikprabhuA** [comment]
Thanks @a1phanumeric  its working fine for me, after i setted the radar range as 1km. [_arViewController setRadarRange:1.0];

**Comment by viral105** [comment]
Thanks @a1phanumeric.

It works for me also.

**Comment by a1phanumeric** [comment]
No problem - you might want to programmatically set that value to the furthest marker every time (that way it'll always work nicely).
